---
- name: Update and upgrade apt packages
  hosts: all
  become: true
  tasks:
    apt:
      upgrade: yes
      update_cache: yes

#- name: Hello World Sample
#  hosts: all
#  tasks:
#    - name: Hello Message
#      debug:
#        msg: "Hello World!"
