---
- hosts: all
  environment: 
  become: yes
  tasks:
  - name: Update APT package cache
    apt: update_cache=yes cache_valid_time=600
  - name: Install nginx
    apt: name=nginx state=present
  tasks:
  - name: copy file
    copy:
       src: 123.txt
       dest: /tmp
